from app.informes.informe_general import informeGeneral
from app.informes.informe_mejor_valoracion import informeMejorValoracion
from app.informes.informe_peor_valoracion import informePeorValoracion
from app.informes.busqueda_por_alumno import busquedaPorAlumno
